const defaults={income1:1800,income2:1500,currency:'$',allocations:[{name:'Vivienda',pct:30,color:'#447d71'},{name:'Ahorro',pct:20,color:'#d3aa54'},{name:'Mercado',pct:15,color:'#cf806f'},{name:'Servicios',pct:10,color:'#79a69c'},{name:'Transporte',pct:10,color:'#8a9cbc'},{name:'Ocio y otros',pct:15,color:'#b7a894'}],market:[{id:1,name:'Arroz',qty:'2 kg',price:8,category:'Alimentos',bought:true},{id:2,name:'Leche',qty:'6 unidades',price:11,category:'Alimentos',bought:false},{id:3,name:'Frutas y verduras',qty:'1 semana',price:32,category:'Alimentos',bought:false},{id:4,name:'Detergente',qty:'1',price:9,category:'Limpieza',bought:false}],transactions:[{id:1,description:'Alquiler',amount:850,type:'expense',category:'Vivienda'},{id:2,description:'Internet y luz',amount:125,type:'expense',category:'Servicios'}]};
let state=JSON.parse(localStorage.getItem('nidoState'))||defaults;let filter='all';
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const money=n=>`${state.currency} ${Number(n||0).toLocaleString('es-ES',{maximumFractionDigits:2})}`;const save=()=>localStorage.setItem('nidoState',JSON.stringify(state));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function totals(){const base=+state.income1 + +state.income2;const extra=state.transactions.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0);const expenses=state.transactions.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0);const saving=base*(state.allocations.find(x=>x.name==='Ahorro')?.pct||0)/100;return{income:base+extra,expenses,saving,available:base+extra-expenses-saving}}
function renderAll(){renderDashboard();renderBudget();renderMarket();renderTransactions()}
function renderDashboard(){const t=totals();$('#availableValue').textContent=money(t.available);$('#incomeMetric').textContent=money(t.income);$('#expenseMetric').textContent=money(t.expenses);$('#savingMetric').textContent=money(t.saving);$('#expensePercent').textContent=`${t.income?Math.round(t.expenses/t.income*100):0}% de ingresos`;$('#savingPercent').textContent=`${state.allocations.find(x=>x.name==='Ahorro').pct}% de meta`;$('#monthStatus').textContent=t.available>=0?'En equilibrio':'Requiere ajustes';$('#availableHint').textContent=t.available>=0?'Después de gastos y ahorro':'Tus gastos superan el plan';$('#allocationBars').innerHTML=state.allocations.slice(0,4).map(x=>`<div class="allocation-row"><label>${x.name}</label><div class="bar"><i style="width:${Math.min(x.pct*2.5,100)}%;background:${x.color}"></i></div><strong>${x.pct}%</strong></div>`).join('');const housing=state.allocations.find(x=>x.name==='Vivienda');$('#smartTip').textContent= housing.pct>35?'⚠️ La vivienda supera el 35%. Consideren reducir otros gastos antes de bajar el ahorro.':'💡 Su distribución reserva ahorro sin descuidar los gastos esenciales.';const bought=state.market.filter(x=>x.bought).length,total=state.market.length,p=total?Math.round(bought/total*100):0;$('#marketRing').style.setProperty('--p',p);$('#marketPercent').textContent=p+'%';$('#marketCount').textContent=`${bought} de ${total} comprados`;$('#marketCost').textContent=`Estimado: ${money(state.market.reduce((a,x)=>a+x.price,0))}`;$('#marketPreview').innerHTML=state.market.slice(0,3).map(x=>`<div class="preview-item ${x.bought?'done':''}"><span>${x.bought?'✓':'○'} ${x.name}</span><strong>${money(x.price)}</strong></div>`).join('')}
function renderBudget(){if(document.activeElement?.matches('#income1,#income2'))return;$('#income1').value=state.income1;$('#income2').value=state.income2;$('#currency').value=state.currency;$('#jointIncome').textContent=money(+state.income1 + +state.income2);$('#budgetRows').innerHTML=state.allocations.map((x,i)=>`<div class="budget-row"><div><strong>${x.name}</strong><small>${money((+state.income1 + +state.income2)*x.pct/100)}</small></div><input class="pct-input" data-index="${i}" type="number" min="0" max="100" value="${x.pct}"><strong>${x.pct}%</strong></div>`).join('');$$('.pct-input').forEach(el=>el.oninput=e=>{state.allocations[e.target.dataset.index].pct=+e.target.value;renderBudget()})}
function renderMarket(){const items=state.market.filter(x=>filter==='all'||(filter==='bought'?x.bought:!x.bought));$('#marketList').innerHTML=items.length?items.map(x=>`<div class="list-item ${x.bought?'done':''}"><input type="checkbox" data-check="${x.id}" ${x.bought?'checked':''}><div class="item-main"><strong>${x.name}</strong><small>${x.qty} · ${x.category}</small></div><span class="item-price">${money(x.price)}</span><button class="delete-btn" data-delete="${x.id}">×</button></div>`).join(''):'<div class="empty">No hay productos en esta vista.</div>';const pending=state.market.filter(x=>!x.bought),bought=state.market.filter(x=>x.bought);$('#pendingItems').textContent=pending.length;$('#pendingTotal').textContent=money(pending.reduce((a,x)=>a+x.price,0));$('#boughtTotal').textContent=money(bought.reduce((a,x)=>a+x.price,0));$$('[data-check]').forEach(el=>el.onchange=e=>{state.market.find(x=>x.id==e.target.dataset.check).bought=e.target.checked;save();renderAll()});$$('[data-delete]').forEach(el=>el.onclick=e=>{state.market=state.market.filter(x=>x.id!=e.target.dataset.delete);save();renderAll()})}
function renderTransactions(){const items=[...state.transactions].reverse();$('#transactionList').innerHTML=items.length?items.map(x=>`<div class="list-item"><span class="metric-icon ${x.type==='income'?'income':'expense'}">${x.type==='income'?'↗':'↘'}</span><div class="item-main"><strong>${x.description}</strong><small>${x.category}</small></div><span class="item-price ${x.type==='income'?'tx-income':'tx-expense'}">${x.type==='income'?'+':'−'} ${money(x.amount)}</span><button class="delete-btn" data-tx-delete="${x.id}">×</button></div>`).join(''):'<div class="empty">Aún no hay movimientos.</div>';$$('[data-tx-delete]').forEach(el=>el.onclick=e=>{state.transactions=state.transactions.filter(x=>x.id!=e.target.dataset.txDelete);save();renderAll()})}
function showView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===id));const titles={inicio:'Buenos días 👋',presupuesto:'Nuestro presupuesto',mercado:'Lista de mercado',movimientos:'Movimientos del mes'};$('#pageTitle').textContent=titles[id];$('.sidebar').classList.remove('open')}
$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
$('#income1').oninput=e=>{state.income1=+e.target.value;$('#jointIncome').textContent=money(+state.income1 + +state.income2)};$('#income2').oninput=e=>{state.income2=+e.target.value;$('#jointIncome').textContent=money(+state.income1 + +state.income2)};$('#currency').onchange=e=>{state.currency=e.target.value;renderAll()};$('#saveBudget').onclick=()=>{const total=state.allocations.reduce((a,x)=>a+x.pct,0);if(total!==100)return toast(`La distribución suma ${total}%. Debe sumar 100%.`);save();renderAll();toast('Presupuesto guardado')};
$('#marketForm').onsubmit=e=>{e.preventDefault();state.market.push({id:Date.now(),name:$('#itemName').value.trim(),qty:$('#itemQty').value.trim()||'1',price:+$('#itemPrice').value||0,category:$('#itemCategory').value,bought:false});e.target.reset();$('#itemQty').value='1';save();renderAll();toast('Producto añadido')};$('#clearBought').onclick=()=>{state.market=state.market.filter(x=>!x.bought);save();renderAll();toast('Productos comprados eliminados')};$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderMarket()});
$('#transactionForm').onsubmit=e=>{e.preventDefault();state.transactions.push({id:Date.now(),description:$('#txDescription').value.trim(),amount:+$('#txAmount').value,type:$('#txType').value,category:$('#txCategory').value});e.target.reset();save();renderAll();toast('Movimiento registrado')};
$('#dateLabel').textContent=new Intl.DateTimeFormat('es',{weekday:'long',day:'numeric',month:'long'}).format(new Date());renderAll();
